how:
	@echo "=========================================="
	@echo "Build:"
	@echo "=========================================="
	@echo "Configure:  cmake -S . -B build"
	@echo "Build:      cmake --build build"
	@echo "Run:        ./build/limit_order_book"
	@echo "Clean:      rm -rf build"
	@echo ""
	@echo "=========================================="
	@echo "Debug Build:"
	@echo "=========================================="
	@echo "Configure:  cmake -S . -B build-debug"
	@echo "Build:      cmake --build build-debug"
	@echo "Run:        ./build/limit_order_book"
	@echo "Clean:      rm -rf build-debug"
